# 2- K Means (K 均值)

K-均值是一类常用的聚类分析方法，在数据挖掘应用中有重要的地位。
- 结合距离函数的概念强调“度量”的概念
- 算法的迭代思想，其体现了EM的思想
- K值确认的难点

下面我们解释其算法细节与python实现。

In [2]:
import numpy as np

In [3]:
def updateCentroid(dataSetRow, centroids):
    """
    更新数据点的聚类标签（即将其分配到最近的中心点对应的簇）

    参数:
    - dataSetRow: 当前数据点的特征向量（不包括标签）
    - centroids: 当前所有中心点的矩阵，最后一列是中心点的标签

    返回:
    - label: 当前数据点所属的簇标签
    """
    # 初始化标签为第一个中心点的标签
    label = centroids[0, -1]
    # 计算当前数据点到第一个中心点的欧氏距离
    minDist = np.linalg.norm(dataSetRow - centroids[0, :-1])

    # 遍历所有中心点，找到距离当前数据点最近的中心点
    for i in range(1, centroids.shape[0]):
        # 计算当前数据点到第i个中心点的欧氏距离
        dist = np.linalg.norm(dataSetRow - centroids[i, :-1])
        # 如果当前距离小于最小距离，则更新最小距离和标签
        if dist < minDist:
            minDist = dist
            label = centroids[i, -1]
            
        print("minDist :\n", minDist)
        return label

def calCentroids(dataSet, k):
    """
    计算新的中心点

    参数:
    - dataSet: 数据集，最后一列是每个数据点的标签
    - k: 簇的数量

    返回:
    - result: 新的中心点矩阵，最后一列是中心点的标签
    """
    # 初始化结果矩阵，用于存储新的中心点
    result = np.zeros((k, dataSet.shape[1]))

    # 遍历每个簇，计算该簇的新中心点
    for i in range(1, k + 1):
        # 获取属于当前簇的所有数据点（不包括标签）
        oneCluster = dataSet[dataSet[:, -1] == i, :-1]
        # 计算当前簇的均值作为新的中心点
        result[i - 1, :-1] = np.mean(oneCluster, axis=0)
        # 设置新中心点的标签
        result[i - 1, -1] = i
        
    return result

In [4]:
def kMeans(X, k, maxIt):    
    numPoints, numDim = X.shape        #横纵坐标
    dataSet = np.zeros((numPoints, numDim + 1))
    dataSet[: ,: -1 ] = X
    #(1)随机产生新的中心点
    centroids = dataSet[np.random.randint(numPoints, size = k), :]
    centroids[:, -1] = range(1, k+1)   #给k个中心点标签赋值为[1，k+1]
    
    iter = 0 #循环次数
    oldCentroids = None  #用来储存旧的中心点    
    while (not np.array_equal(oldCentroids, centroids) or iter <= maxIt):
        print("iterations:\n ",iter)
        print("dataSet: \n",dataSet)
        print("centroids:\n",centroids)
        
        #用copy的原因是进行深度复制，简单赋值相当于同时指向一个地址（
        oldCentroids = np.copy(centroids)
        iter += 1
        
        #(2)更新中心点
        numPoints, numDim = dataSet.shape
        for i in range(0,numPoints):
            dataSet[i,-1] = updateCentroid(dataSet[i, :-1],centroids)
        
        #(3)计算新的中心点
        centroids = calCentroids(dataSet, k)
    
    return dataSet

In [5]:
x1 = np.array([1, 1])
x2 = np.array([2, 1])
x3 = np.array([4, 3])
x4 = np.array([5, 4])
testX = np.vstack((x1, x2, x3, x4))

result = kMeans(testX, 2, 10)
print("final result: \n\n",result)

iterations:
  0
dataSet: 
 [[1. 1. 0.]
 [2. 1. 0.]
 [4. 3. 0.]
 [5. 4. 0.]]
centroids:
 [[1. 1. 1.]
 [2. 1. 2.]]
minDist :
 0.0
minDist :
 0.0
minDist :
 2.8284271247461903
minDist :
 4.242640687119285
iterations:
  1
dataSet: 
 [[1. 1. 1.]
 [2. 1. 2.]
 [4. 3. 2.]
 [5. 4. 2.]]
centroids:
 [[1.         1.         1.        ]
 [3.66666667 2.66666667 2.        ]]
minDist :
 0.0
minDist :
 1.0
minDist :
 0.4714045207910319
minDist :
 1.885618083164127
iterations:
  2
dataSet: 
 [[1. 1. 1.]
 [2. 1. 1.]
 [4. 3. 2.]
 [5. 4. 2.]]
centroids:
 [[1.5 1.  1. ]
 [4.5 3.5 2. ]]
minDist :
 0.5
minDist :
 0.5
minDist :
 0.7071067811865476
minDist :
 0.7071067811865476
iterations:
  3
dataSet: 
 [[1. 1. 1.]
 [2. 1. 1.]
 [4. 3. 2.]
 [5. 4. 2.]]
centroids:
 [[1.5 1.  1. ]
 [4.5 3.5 2. ]]
minDist :
 0.5
minDist :
 0.5
minDist :
 0.7071067811865476
minDist :
 0.7071067811865476
iterations:
  4
dataSet: 
 [[1. 1. 1.]
 [2. 1. 1.]
 [4. 3. 2.]
 [5. 4. 2.]]
centroids:
 [[1.5 1.  1. ]
 [4.5 3.5 2. ]]
minDist :
 